#theme: jekyll-theme-cayman
remote-theme: mmistakes/minimal-mistakes
title: Aswinkumar Prakashkumar
description:
  1630 228th ST SE, Apt I106, Bothell, WA, 98021 | aswinkumar.p@outlook.com | 612-469-1282
  
