#Author: Aswinkumar Prakashkumar 
#Email: aswinkumar.p@outlook.com
#**********************IMPORTANT*********************
#Please read before making changes to this file. 
#This file controls how the website is rendered. It contains the navigation, pages, and links that are common to all pages in the website. 
#This file is change it once and forget space, there should be no changes until you are revamping the overall design of the website. 
#If you run into Jekyll Build Error, please use YAML Lint - YAML Validator to find out what's wrong and fix before making further changes. 

title: Aswinkumar Prakashkumar
email: aswinkumar.p@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  
#twitter_username: username
github_username: akprakashkumar
minimal_mistakes_skin: dirt
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Aswinkumar Prakashkumar"
  avatar : "/assets/images/AK_DisplayPicture.jpg"
  bio    : "Geek, Tech-Evangelist, Foodie, Travel-Lover, Father & Husband"
  links:
    #- label: "Website"
    #  icon: "fas fa-fw fa-link"
    #  url: "https://aswinkumar.in"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/akprakashkumar"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/pkaswinkumar"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/pkaswinkumar"
footer:
  links:
    - label: "GitHub"
      icon: <i class="fab fa-fw fa-github" style="color:#FFFFFF;"><!-- icon --></i>
      url: "https://github.com/akprakashkumar"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/pkaswinkumar"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/pkaswinkumar"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
  
tag_archive:
  type: liquid
  path: /tags/